package com.example.forca

class Palavras {
    //lista com todas as categorias e palavras para o jogo
    val lista = mutableMapOf(
        "Alimentos" to "BANANA",
        "Alimentos" to "LARANJA",
        "Alimentos" to "OVO",
        "Alimentos" to "UVA",
        "Alimentos" to "PERA",
        "Alimentos" to "BATATA",
        "Alimentos" to "ARROZ",
        "Alimentos" to "FRANGO",
        "Alimentos" to "CARNE",

        "Objetos" to "CADEIRA",
        "Objetos" to "MESA",
        "Objetos" to "COMPUTADOR",
        "Objetos" to "MOUSE",
        "Objetos" to "ESTANTE",
        "Objetos" to "CARRO",
        "Objetos" to "BICICLETA",
        "Objetos" to "TELEVISÃO",

        "Ação" to "CORRER",
        "Ação" to "ANDAR",
        "Ação" to "COMER",
        "Ação" to "CAMINHAR",
        "Ação" to "CONVERSAR",
        "Ação" to "FAZER",
        "Ação" to "COZINHAR",
        "Ação" to "CANTAR",
        "Ação" to "TOCAR",
        "Ação" to "MERGULHAR",

        "Cep" to "BRASIL",
        "Cep" to "PORTUGAL",
        "Cep" to "INGLATERRA",
        "Cep" to "ESLOVENIA",
        "Cep" to "IRLANDA",
        "Cep" to "JAPÃO",
        "Cep" to "CHINA",
        "Cep" to "ORLANDO",
        "Cep" to "CANADA",

        "Filme" to "TITANIC",
        "Filme" to "MEGAMENTE",
        "Filme" to "INTERESTELAR",
        "Filme" to "ENROLADOS",
        "Filme" to "RATATOUILLE",
        "Filme" to "MADAGASCAR",
        "Filme" to "SHEREK",

        "Marca" to "GUCCI",
        "Marca" to "LACOSTE",
        "Marca" to "PRADA",
        "Marca" to "BMW",
        "Marca" to "DIOR",
        "Marca" to "VIVARA",
        "Marca" to "NIKE",
        "Marca" to "ADIDAS",
        "Marca" to "ROLEX",
        "Marca" to "MERCEDES",
        "Marca" to "LUPO",
        "Marca" to "AUDI",
        "Marca" to "VANS",
        "Marca" to "DISNEY",
        "Marca" to "INTEL",
        "Marca" to "PEUGEOT",

        "Esporte" to "FUTEBOL",
        "Esporte" to "BASQUETE",
        "Esporte" to "HANDEBOL",
        "Esporte" to "FUTSAL",
        "Esporte" to "GOLFE",
        "Esporte" to "SKATE",
        "Esporte" to "SURFE",
        "Esporte" to "XADREZ",

    )
}